export const appState = {
    isProcessing: true,
    isSystemConnected: true,
    currentIncomingRate: 0,
    currentProcessedRate: 0,
    currentErrorRate: 0,
    averageLatency: 0,
    batchRetrySize: 100,
    chosenRetryStrategy: 'immediate',
    allRecordedErrors: [],
    displayableErrors: [],
    activePage: 1,
    logsPerPage: 10,
    currentSearchTerm: '',
    activeErrorTypeFilter: '',
    activeTimeframeFilter: '5m',
    chartsReady: false,
};